server:
  port: 8766

spring:
  application:
    name: config
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/zhaofan10086/springcloud-config.git
          search-paths: /
          username:
          password:
          skip-ssl-validation: true #放弃安全认证
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
