server:
  port: 8777

spring:
  application:
    name: log-recevie
  data:
    mongodb:
      host: localhost
      port: 27017
      database: 20201029
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    publisher-confirm-type: correlated
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual
      direct:
        acknowledge-mode: manual
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: rabbit
  sleuth:
    sampler:
      probability: 1

logging:
  config: classpath:logback-spring.xml
  file:
    path: D:/tmp/log