server:
  port: 8761  #设置端口号

  #配置eureka
eureka:
  instance:
    hostname: localhost #配置实例地址
  client:
    register-with-eureka: false
    fetch-registry: false #阻止eureka自身项目注册到注册中心
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
  server:
    enable-self-preservation: false # 关闭自我保护机制 ， 默认为true开启

spring:
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: rabbit
  sleuth:
    sampler:
      probability: 1
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

